// <auto-generated />
namespace Ktcs.DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fixForCourse_CourseTypeDetail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixForCourse_CourseTypeDetail));
        
        string IMigrationMetadata.Id
        {
            get { return "201607102225203_fixForCourse_CourseTypeDetail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
