//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ktcs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public string UserID { get; set; }
        public string Password { get; set; }
        public string adminemail { get; set; }
        public string AdminInitials { get; set; }
        public string AdminFName { get; set; }
        public string AdminLName { get; set; }
        public string AdminPhone { get; set; }
        public string AdminWebsite { get; set; }
        public string AdminFax { get; set; }
        public string AdminCompany { get; set; }
        public string SysAdmin { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public int ReportDateRange { get; set; }
    }
}
