//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ktcs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassRequest
    {
        public int RequestID { get; set; }
        public int StudentID { get; set; }
        public int ScheduledClassID { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<System.DateTime> ApprovalSent { get; set; }
        public Nullable<System.DateTime> ApprovalReceived { get; set; }
        public string Denied { get; set; }
        public string Withdrew { get; set; }
        public Nullable<System.DateTime> Enrolled { get; set; }
        public string WithdrawReason { get; set; }
    }
}
