//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ktcs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComContact
    {
        public int ComContactID { get; set; }
        public int CompanyID { get; set; }
        public string ComConTitle { get; set; }
        public string ComConFName { get; set; }
        public string ComConLName { get; set; }
        public string ComConAddress { get; set; }
        public string ComConAddress2 { get; set; }
        public string ComConCity { get; set; }
        public string ComConState { get; set; }
        public string ComConZip { get; set; }
        public string ComConPhone { get; set; }
        public string ComConPhone2 { get; set; }
        public string ComConEmail { get; set; }
        public string ComConEmail2 { get; set; }
        public string ComConFax { get; set; }
        public string ComConCountry { get; set; }
    }
}
