//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ktcs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public int CompanyID { get; set; }
        public string comName { get; set; }
        public string comAddress { get; set; }
        public string comAddress2 { get; set; }
        public string comCity { get; set; }
        public string comState { get; set; }
        public string comZip { get; set; }
        public string comcountry { get; set; }
        public string comphone { get; set; }
        public string comfax { get; set; }
        public string comMapLink { get; set; }
        public string billname { get; set; }
        public string billaddress { get; set; }
        public string billaddress2 { get; set; }
        public string billcity { get; set; }
        public string billstate { get; set; }
        public string billzip { get; set; }
        public string billphone { get; set; }
        public string billfax { get; set; }
        public string billcountry { get; set; }
        public string logo { get; set; }
        public string billemail { get; set; }
    }
}
