//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ktcs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public int contactID { get; set; }
        public int vendorid { get; set; }
        public string contitle { get; set; }
        public string conFName { get; set; }
        public string conLName { get; set; }
        public string conaddress { get; set; }
        public string concity { get; set; }
        public string constate { get; set; }
        public string conzip { get; set; }
        public string conphone { get; set; }
        public string conphone2 { get; set; }
        public string conemail { get; set; }
        public string conemail2 { get; set; }
        public string confax { get; set; }
        public string concountry { get; set; }
        public string conext1 { get; set; }
        public string conext2 { get; set; }
    }
}
