//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ktcs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CourseType()
        {
            this.CourseTypeDetails = new HashSet<CourseTypeDetail>();
        }
    
        public int courseTypeID { get; set; }
        public string courseType1 { get; set; }
        public int AreaID { get; set; }
        public string pageNotes { get; set; }
        public Nullable<int> visibleInFlyout { get; set; }
        public string flyoutText { get; set; }
    
        public virtual area area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseTypeDetail> CourseTypeDetails { get; set; }
    }
}
