//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ktcs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.ScheduledClasses = new HashSet<ScheduledClass>();
            this.BrandCategories = new HashSet<BrandCategory>();
            this.TopicCategories = new HashSet<TopicCategory>();
        }
    
        public string courseNumber { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string prereq { get; set; }
        public string duration { get; set; }
        public Nullable<int> courseTypeDetailID { get; set; }
        public string comments { get; set; }
        public string inscomments { get; set; }
        public string overview { get; set; }
        public int basePriceID { get; set; }
        public string courseware { get; set; }
        public string coursewarevendor { get; set; }
        public Nullable<decimal> coursewarecost { get; set; }
        public string coursewarenotes { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
        public Nullable<System.DateTime> lastupdate { get; set; }
        public string instructorNotes { get; set; }
        public string vendorwebsite { get; set; }
        public Nullable<int> isvisable { get; set; }
        public Nullable<int> visibleInFlyout { get; set; }
    
        public virtual BasePrice BasePrice { get; set; }
        public virtual CourseTypeDetail CourseTypeDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduledClass> ScheduledClasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BrandCategory> BrandCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TopicCategory> TopicCategories { get; set; }
    }
}
