//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ktcs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        public int ConfirmationNum { get; set; }
        public Nullable<System.DateTime> Enrolled { get; set; }
        public Nullable<System.DateTime> Confirmation { get; set; }
        public Nullable<System.DateTime> Reminder { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public string invoice { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> MTSfee { get; set; }
        public int statusID { get; set; }
        public Nullable<decimal> Amountdue { get; set; }
        public int StudentID { get; set; }
        public int ScheduledClassID { get; set; }
        public string cancellationNum { get; set; }
        public Nullable<System.DateTime> cancellationDate { get; set; }
        public Nullable<System.DateTime> dateDue { get; set; }
        public string mgrConfirmation { get; set; }
        public string conarchived { get; set; }
        public Nullable<decimal> DiscountDollars { get; set; }
    
        public virtual ScheduledClass ScheduledClass { get; set; }
        public virtual Status Status { get; set; }
        public virtual student student { get; set; }
    }
}
