//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ktcs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense
    {
        public int ExpenseID { get; set; }
        public int VendorID { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> Qty { get; set; }
        public string Description { get; set; }
        public Nullable<int> ExpenseTypeID { get; set; }
        public Nullable<int> ScheduledClassID { get; set; }
        public string VenInvoiceNum { get; set; }
        public Nullable<System.DateTime> VenInvoiceDate { get; set; }
        public string VenInvoicePaid { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> Shipping { get; set; }
    
        public virtual ExpenseType ExpenseType { get; set; }
    }
}
