//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ktcs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class instructorCert
    {
        public string insCertification { get; set; }
        public string instructorID { get; set; }
    }
}
