//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ktcs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Location()
        {
            this.ScheduledClasses = new HashSet<ScheduledClass>();
        }
    
        public int LocationID { get; set; }
        public string locaddress { get; set; }
        public string loccity { get; set; }
        public string locstate { get; set; }
        public string loczip { get; set; }
        public string locnotes { get; set; }
        public string locName { get; set; }
        public Nullable<int> VendorID { get; set; }
        public string locmapLink { get; set; }
        public string locphone { get; set; }
        public string loccountry { get; set; }
    
        public virtual vendor vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduledClass> ScheduledClasses { get; set; }
    }
}
