//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ktcs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager
    {
        public int ManagerID { get; set; }
        public string mgrFName { get; set; }
        public string mgrLName { get; set; }
        public string mgrPhone { get; set; }
        public string mgrEmail { get; set; }
        public string mgrFax { get; set; }
    }
}
