//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ktcs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduledClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScheduledClass()
        {
            this.Enrollments = new HashSet<Enrollment>();
        }
    
        public int ScheduledClassID { get; set; }
        public string courseNumber { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public string startTime { get; set; }
        public string endTime { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> MarketRate { get; set; }
        public string ispublic { get; set; }
        public Nullable<decimal> KTCSRate { get; set; }
        public string KTCScourse { get; set; }
        public string startDateconfirmed { get; set; }
        public string bookOrderMade { get; set; }
        public string insTestReminder { get; set; }
        public string bookOrderRecieved { get; set; }
        public string insconfirmed { get; set; }
        public string locconfirmed { get; set; }
        public Nullable<short> MaxStudents { get; set; }
        public int locationID { get; set; }
        public string InstructorID { get; set; }
        public int CompanyID { get; set; }
        public int SurveyID { get; set; }
        public string Mirrored { get; set; }
        public string MirroredWebsite { get; set; }
    
        public virtual Course Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enrollment> Enrollments { get; set; }
        public virtual Instructor Instructor { get; set; }
        public virtual Location Location { get; set; }
        public virtual Survey Survey { get; set; }
    }
}
