//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ktcs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public student()
        {
            this.Enrollments = new HashSet<Enrollment>();
            this.WaitLists = new HashSet<WaitList>();
        }
    
        public int StudentID { get; set; }
        public string stuLName { get; set; }
        public string stuFName { get; set; }
        public string stuEmail { get; set; }
        public string Password { get; set; }
        public string stuHomePhone { get; set; }
        public string stuInternationalCode { get; set; }
        public string stuProductArea { get; set; }
        public int ManagerID { get; set; }
        public int CompanyID { get; set; }
        public string stupassword { get; set; }
        public int authorityID { get; set; }
        public string stuWorkPhone { get; set; }
        public string stuCountry { get; set; }
        public string stuJobTitle { get; set; }
        public string stuCity { get; set; }
        public string stustate { get; set; }
        public string stuaddress { get; set; }
        public string stuaddress2 { get; set; }
        public string stuzip { get; set; }
        public Nullable<int> ReferredByID { get; set; }
        public string stufax { get; set; }
        public string CostCenter { get; set; }
        public string BillName { get; set; }
        public string BillAddress { get; set; }
        public string BillAddress2 { get; set; }
        public string BillCity { get; set; }
        public string BillState { get; set; }
        public string BillZip { get; set; }
        public string BillCountry { get; set; }
        public string BillPhone { get; set; }
        public string BillFax { get; set; }
        public string BillEmail { get; set; }
        public string BillInternationalCode { get; set; }
        public string OtherCompany { get; set; }
        public string OtherReferredBy { get; set; }
        public string OtherManager { get; set; }
        public string OtherManagerPhone { get; set; }
        public string mailList { get; set; }
        public string UserID { get; set; }
        public Nullable<byte> ClassesTaken { get; set; }
        public string blockReminder { get; set; }
        public string other { get; set; }
        public string stuarchived { get; set; }
        public string Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enrollment> Enrollments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WaitList> WaitLists { get; set; }
    }
}
