//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ktcs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentNote2
    {
        public int NoteID { get; set; }
        public int StudentID { get; set; }
        public System.DateTime NoteDate { get; set; }
        public string Notes { get; set; }
        public int NoteTypeID { get; set; }
        public string followup { get; set; }
        public string AdminInitials { get; set; }
        public Nullable<System.DateTime> FollowUpDate { get; set; }
        public string ToDoFor { get; set; }
        public string Priority { get; set; }
    }
}
