//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ktcs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaitList
    {
        public int WaitListID { get; set; }
        public int StudentID { get; set; }
        public string CourseNumber { get; set; }
        public string TimeFrame { get; set; }
        public string Comments { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual student student { get; set; }
    }
}
